type: docker
kind: pipeline
name: test

trigger:
  event: [push]

steps:
  - name: test
    image: node:14.2.0-slim
    commands:
      - apt update && apt install python g++ build-essential -y
      - yarn install --pure-lockfile
      - yarn lint
    depends_on: [clone]
---
type: docker
kind: pipeline
name: build

trigger:
  event: [push]
  branch: [master]

steps:
  - name: builder
    image: plugins/docker
    settings:
      target: builder
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/nest-nuxt-boilerplate
      tags: builder
      cache_from:
        - quay.io/zebbra/nest-nuxt-boilerplate:builder
      custom_labels: [quay.expires-after=30d]
      mtu: 1316

  - name: release
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/nest-nuxt-boilerplate
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
      cache_from:
        - quay.io/zebbra/nest-nuxt-boilerplate:builder
        - quay.io/zebbra/nest-nuxt-boilerplate:latest
      mtu: 1316
---
type: docker
kind: pipeline
name: deploy

trigger:
  event: [push]
  branch: [master]

steps:
  - name: production
    image: pelotech/drone-helm3
    depends_on:
      - test
      - build
    settings:
      kube_api_server: https://kubernetes.default
      kube_token: { from_secret: kubernetes_token }
      chart: ./deploy/nest-nuxt-boilerplate
      release: nest-nuxt-boilerplate
      namespace: demo
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7}
      values_files: [deploy/values.yaml]
      reuse_values: false
      skip_tls_verify: true
