apiVersion: v1
kind: Secret
metadata:
  name: nest-nuxt-boilerplate
  namespace: demo
type: Opaque
data:
  TYPEORM_URL: cG9zdGdyZXM6Ly9wb3N0Z3Jlc0Bsb2NhbGhvc3Q6NTQzMi9uZXN0LW51eHQtYm9pbGVycGxhdGU=
  SENTRY_DSN: eW91cl9zZW50cnlfZHNu
