apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nest-nuxt-boilerplate.fullname" . }}
  labels:
    {{- include "nest-nuxt-boilerplate.labels" . | nindent 4 }}
data:
  SENTRY_ENVRIONMENT: production
  TYPEORM_MIGRATIONS: "dist/db/migrate/*.js"
  HTTP_GRAPHQL_ENDPOINT: https://nest-nuxt-boilerplate.demo.zebbra.ch/graphql
  WS_GRAPHQL_ENDPOINT: ws://nest-nuxt-boilerplate.demo.zebbra.ch/graphql
