apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nest-nuxt-boilerplate.fullname" . }}
  labels:
    {{- include "nest-nuxt-boilerplate.labels" . | nindent 4 }}
data:
  ACCESS_CONTROL_ALLOW_ORIGIN: "https://nest-nuxt-boilerplate.demo.zebbra.ch"
  TYPEORM_MIGRATIONS: "dist/db/migrate/*.js"
  SENTRY_ENVIRONMENT: production
