apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nest-nuxt-boilerplate.fullname" . }}-db-migrate
  labels:
{{ include "nest-nuxt-boilerplate.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ include "nest-nuxt-boilerplate.fullname" . }}-db-migrate
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TYPEORM_ENTITIES
              value: {{ .Values.config.TYPEORM_ENTITIES | quote }}
            - name: TYPEORM_MIGRATIONS
              value: {{ .Values.config.TYPEORM_MIGRATIONS | quote }}
            - name: TYPEORM_URL
              value: {{ .Values.secrets.TYPEORM_URL | quote }}

          command: ["yarn", "typeorm", "migration:run"]
