apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "nest-nuxt-boilerplate.fullname" . }}-db-migrate
  labels:
{{ include "nest-nuxt-boilerplate.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ include "nest-nuxt-boilerplate.fullname" . }}-db-migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: db-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "nest-nuxt-boilerplate.fullname" . }}
            - configMapRef:
                name: {{ include "nest-nuxt-boilerplate.fullname" . }}

          command: ["yarn", "db:migrate"]
